start_date = "2023-01-01"
end_date = "2025-01-31"
year_list = [2023, 2024, 2025]
query_terms_list = [
    [
       'LLM', 
       'large language model',
       'NLP', 
       'natural language processing',
       'GPT', 
       'chatGPT', 
       'transformer',
       'BERT',
       'Bidirectional Encoder Representation',
       'RAG',
       'retrieval-augmented generation',
       'retrieval augmented generation',
       'generative AI',
       'AI assistant',
       'prompt',
       'chatbot',
       'prompt engineering',
       'attention mechanism',
       'chain-of-thought',
       'chain of thought'
    ],
    [
       'genomic',
       'genetic',
       'inherited',
       'hereditary',
       'heredity',
       'inheritance',
       'heritability',
        "disease subtype",
       'NGS',
       'next-generation sequencing',
       'next generation sequencing',
       'genome sequencing',
       'phenotype description',
       'variant interpretation',
       'complex trait',
       'medicine',
       'medical',
       'diagnosis',
       'diagnostic',
       'clinical',
       "clinical decision", 
       'syndrome',
    ],
]
DATA_DIR='data'